substitutions:
  _REGION: us-central1
  _REPOSITORY: polititrack
  _IMAGE: runtime-v2
  _TAG: manual

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/runtime-v2/Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}
