/* The Overview downloads only the additive insights model. Full ledgers are lazy. */
(() => {
  "use strict";
  const {el,esc,helpButton,numeric,number,money,percent,title,date,age,safeUrl,link,workflowUrl,checkedJson,statusText,fact,emptySignals,signalCard,healthCards,replay,brief}=PT;
  const PAGE_SIZE = 50;
  const state={model:null,data:{},tables:{},loading:false,section:"overview",record:"filings",nextRefreshAt:Date.now()+300000,renderedAt:null};
  const openDialog=PT.setupDialogsAndTooltips();
  const notifications=new PolitiTrackNotifications({onChange:()=>renderNotifications()});
  const definitions={
    filings:{title:"Filing inventory",file:"filings",date:"filed_date",dates:["filed_date","first_seen_utc"],filters:["source","status"],search:"Filer, agency, district, report…",columns:[["filed_date","Filed","date"],["source","Source"],["filer","Filer"],["title","Role"],["status","Coverage status"],["transaction_count","Parsed rows","number"],["source_url","Official filing","link"]]},
    transactions:{title:"Parsed transactions",file:"transactions",date:"transaction_date",dates:["transaction_date","filed_date","observed_at_utc"],filters:["source","transaction_type"],search:"Ticker, company, filer, owner…",columns:[["transaction_date","Transaction date","date"],["filed_date","Filing date","date"],["observed_at_utc","Observed","date"],["source","Source"],["filer","Filer"],["owner","Owner"],["transaction_type","Type"],["ticker","Ticker / asset"],["amount","Disclosed range"],["source_url","Filing","link"]]},
    reviews:{title:"Review queue",file:"pending-reviews",date:"filed_date",dates:["filed_date","observed_at_utc"],filters:["source"],search:"Filer, agency, reason…",columns:[["filed_date","Filed","date"],["source","Source"],["filer","Filer"],["agency","Agency / title"],["reason","Review reason"],["source_url","Official page","link"]]},
    ai:{title:"All AI analyses",file:"ai-analyses",date:"analyzed_at_utc",dates:["analyzed_at_utc","transaction_date","filed_date","observed_at_utc"],filters:["classification","source"],search:"Ticker, filer, owner, rationale…",columns:[["analyzed_at_utc","Analyzed","date"],["ticker","Ticker / asset"],["classification","Classification"],["final_score","Score","number"],["filer","Filer / owner"],["transaction_date","Transaction","date"],["filed_date","Filed","date"],["observed_at_utc","Observed","date"],["base_score","Base score","number"],["investor_edge_modifier","Modifier","number"],["investor_edge_observation_count","Observations","number"],["investor_edge_score","Investor Edge","number"],["investor_edge_confidence_label","Edge confidence"],["investor_edge_relevant_followable_alpha","Followable alpha","percent"],["investor_edge_sector_alpha","Sector edge","percent"],["ai.analysis_summary","Analysis"],["source_url","Evidence","evidence"]]},
    portfolio:{title:"Paper positions",file:"paper-portfolio",date:"opened_at_utc",dates:["opened_at_utc","last_updated_utc"],filters:["status"],search:"Ticker, filer, owner…",columns:[["opened_at_utc","Opened","date"],["ticker","Ticker"],["status","Status"],["filer","Filer / owner"],["entry_price","Entry","money"],["current_price","Current","money"],["quantity","Quantity","number"],["unrealized_pnl","Unrealized P&L","money"],["realized_pnl","Realized P&L","money"],["return_percent","Return","percent"],["source_url","Filing","link"]]},
    runs:{title:"Retained run history",file:"runs",date:"finished_utc",dates:["finished_utc","started_utc"],filters:["branch"],search:"Branch, errors, run…",columns:[["finished_utc","Finished","date"],["branch","Branch"],["success","Result","status"],["new_filing_counts","New filings","sum"],["completed_count","AI completed","number"],["errors","Errors","array"],["run_url","GitHub run","link"]]}
  };
  const columnHelp = Object.freeze({
    final_score: "finalScore", base_score: "baseScore", investor_edge_modifier: "edgeModifier",
    investor_edge_score: "investorEdge", investor_edge_confidence_label: "edgeConfidence",
    investor_edge_relevant_followable_alpha: "followableAlpha", investor_edge_sector_alpha: "sectorEdge"
  });
  function get(row,path){return path.split(".").reduce((v,k)=>v&&typeof v==="object"?v[k]:undefined,row);}
  const dateLabel=key=>({filed_date:"Filing date",transaction_date:"Transaction date",observed_at_utc:"PolitiTrack observation date",first_seen_utc:"First observed date",analyzed_at_utc:"Analysis date",opened_at_utc:"Position opened date",last_updated_utc:"Valuation date",finished_utc:"Run finished date",started_utc:"Run started date"}[key]||title(key));
  function initTables(){for(const [key,def] of Object.entries(definitions)){
    state.tables[key]={query:"",filters:{},page:0,sort:def.date,descending:true,dateBasis:def.date,from:"",to:""};
    el(`panel-${key}`).innerHTML=`<div class="panel-header"><h3>${def.title}</h3><a href="data/${def.file}.csv" download>Download CSV ↓</a>${key==="runs"?'<a href="data/ai-runs.csv" download>AI runs CSV ↓</a>':""}</div><div class="controls"><label>Search<input id="${key}-search" type="search" placeholder="${esc(def.search)}"></label>${def.filters.map(field=>`<label>${title(field)}<select id="${key}-${field=== "transaction_type"?"type":field}"><option value="">All ${esc(title(field).toLowerCase())}</option></select></label>`).join("")}</div><div class="date-controls"><label>Date basis<select id="${key}-date-basis">${def.dates.map(d=>`<option value="${d}">${dateLabel(d)}</option>`).join("")}</select></label><label>From<input id="${key}-date-from" type="date"></label><label>Through<input id="${key}-date-to" type="date"></label><button id="${key}-clear">Clear filters</button></div><p id="${key}-count-label" class="result-count" role="status">Open this section to load retained records.</p><div class="table-wrap" tabindex="0" role="region" aria-label="${def.title} table, scroll for additional columns"><table><caption>${def.title} · click a column heading to sort</caption><thead><tr>${def.columns.map(([field,label])=>`<th scope="col" data-sort-field="${field}"><button data-sort="${field}" data-table="${key}">${label} ↕</button>${columnHelp[field]?` ${helpButton(columnHelp[field],label)}`:""}</th>`).join("")}</tr></thead><tbody id="${key}-body"></tbody></table></div><div class="pagination"><button id="${key}-previous">← Previous</button><span id="${key}-page"></span><button id="${key}-more">Next →</button></div>`;
    let timer;el(`${key}-search`).addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(()=>{state.tables[key].query=el(`${key}-search`).value.toLowerCase();state.tables[key].page=0;renderTable(key);},180);});
    for(const field of def.filters)el(`${key}-${field==="transaction_type"?"type":field}`).addEventListener("change",e=>{state.tables[key].filters[field]=e.target.value;state.tables[key].page=0;renderTable(key);});
    for(const [suffix,prop] of [["date-basis","dateBasis"],["date-from","from"],["date-to","to"]])el(`${key}-${suffix}`).addEventListener("change",e=>{state.tables[key][prop]=e.target.value;state.tables[key].page=0;renderTable(key);});
    el(`${key}-previous`).onclick=()=>{state.tables[key].page=Math.max(0,state.tables[key].page-1);renderTable(key);};
    el(`${key}-more`).onclick=()=>{state.tables[key].page++;renderTable(key);};
    el(`${key}-clear`).onclick=()=>{const t=state.tables[key];t.query="";t.filters={};t.page=0;t.from="";t.to="";el(`${key}-search`).value="";for(const field of def.filters)el(`${key}-${field==="transaction_type"?"type":field}`).value="";el(`${key}-date-from`).value="";el(`${key}-date-to`).value="";renderTable(key);};
  }
  document.addEventListener("click",e=>{const b=e.target.closest("[data-sort]");if(!b)return;const t=state.tables[b.dataset.table];t.descending=t.sort===b.dataset.sort?!t.descending:false;t.sort=b.dataset.sort;t.page=0;renderTable(b.dataset.table);});}
  function cell(row,field,type){let v=get(row,field);if(["investor_edge_relevant_followable_alpha","investor_edge_sector_alpha","investor_edge_score"].includes(field)&&(["insufficient_data","unavailable","disabled","error","neutral"].includes(row.investor_edge_status)||row.investor_edge?.minimum_sample_met===false))v=null;if(field==="final_score")v=v??row.score;
    if(type==="date")return esc(date(v));if(type==="money")return esc(money(v));if(type==="percent")return esc(percent(v));if(type==="number")return esc(number(v));if(type==="link")return link(v,field==="run_url"?"Open run":"Official filing");
    if(type==="evidence")return link(v)+ (Array.isArray(row.ai?.evidence_sources)?row.ai.evidence_sources.filter(s=>s&&typeof s==="object"&&typeof s.url==="string").slice(0,4).map(s=>link(s.url,s.title||"Evidence")).join(""):"");
    if(type==="status"){if(row.errors && (Array.isArray(row.errors)?row.errors.length:typeof row.errors==="object"?Object.keys(row.errors).length:String(row.errors).trim().length))v=false;return `<span class="status ${v===true?"success":v===false?"failure":"unknown"}">${v===true?"✓ Success":v===false?"! Failed":"◌ Unknown"}</span>`;}
    if(type==="array")return esc(Array.isArray(v)?v.join("; ")||"None recorded":v||"None recorded");
    if(type==="sum")return v&&typeof v==="object"&&!Array.isArray(v)&&Object.values(v).every(x=>numeric(x)!==null)?number(Object.values(v).reduce((a,b)=>a+Number(b),0)):"Unavailable";
    if(field==="ticker")return `<strong>${esc(v||"Unresolved")}</strong><small>${esc(row.asset||"")}</small>`;
    if(field==="filer")return `<strong>${esc(v||"Unavailable")}</strong><small>${esc([row.owner,row.title,row.agency].filter(Boolean).join(" · "))}</small>${(row.is_synthetic_test===true||["true","1","yes"].includes(String(row.is_synthetic_test).toLowerCase())||/TEST[:_-]/i.test(String(row.trade_id||row.filing_key||row.analysis_id||row.report_id||"")))?'<small class="caution">TEST — Temporary Run Simulation</small>':""}`;
    if(field==="status"||field==="classification")return `<span class="badge">${esc(title(v||"Unknown"))}</span>`;
    return esc(v===null||v===undefined||v===""?"Unavailable":typeof v==="object"?JSON.stringify(v):v);
  }
  function renderTable(key){const def=definitions[key],t=state.tables[key],data=state.data[key];if(!Array.isArray(data))return;
    const rows=data.filter(r=>(!t.query||JSON.stringify(r).toLowerCase().includes(t.query))&&Object.entries(t.filters).every(([f,v])=>!v||String(r[f])===v)&&(!t.from||String(r[t.dateBasis]||"").slice(0,10)>=t.from)&&(!t.to||(r[t.dateBasis]&&String(r[t.dateBasis]).slice(0,10)<=t.to)));
    rows.sort((a,b)=>{const av=get(a,t.sort),bv=get(b,t.sort),an=numeric(av),bn=numeric(bv);return (an!==null&&bn!==null?an-bn:String(av??"").localeCompare(String(bv??"")))*(t.descending?-1:1);});
    t.page=Math.min(t.page,Math.max(0,Math.ceil(rows.length/PAGE_SIZE)-1));const start=t.page*PAGE_SIZE,shown=rows.slice(start,start+PAGE_SIZE);
    el(`${key}-body`).innerHTML=shown.length?shown.map(row=>`<tr>${def.columns.map(([field,label,type])=>`<td>${cell(row,field,type)}</td>`).join("")}</tr>`).join(""):`<tr><td colspan="${def.columns.length}" class="empty">${key==="portfolio"&&!data.length?"No open paper positions. No performance implied.":"No matching records."}</td></tr>`;
    el(`${key}-count-label`).textContent=`${rows.length?start+1:0}–${Math.min(start+PAGE_SIZE,rows.length)} of ${number(rows.length)} matching records · date basis: ${dateLabel(t.dateBasis)}`;
    el(`${key}-page`).textContent=`Page ${t.page+1} of ${Math.max(1,Math.ceil(rows.length/PAGE_SIZE))}`;el(`${key}-previous`).disabled=t.page===0;el(`${key}-more`).disabled=start+PAGE_SIZE>=rows.length;
    el(`panel-${key}`).querySelectorAll("th[data-sort-field]").forEach(th=>th.setAttribute("aria-sort",th.dataset.sortField===t.sort?(t.descending?"descending":"ascending"):"none"));
  }
  function populateFilters(key){for(const field of definitions[key].filters){const select=el(`${key}-${field==="transaction_type"?"type":field}`),value=state.tables[key].filters[field]||"";select.innerHTML=`<option value="">All ${title(field).toLowerCase()}</option>`+[...new Set(state.data[key].map(row=>String(row[field]??"")).filter(Boolean))].sort().map(v=>`<option value="${esc(v)}">${esc(title(v))}</option>`).join("");select.value=value;}}
  const pendingTables={};
  async function fetchTable(key){if(pendingTables[key])return pendingTables[key];pendingTables[key]=(async()=>{const rows=await checkedJson(`data/${definitions[key].file}.json`);if(!Array.isArray(rows)||rows.some(r=>!r||typeof r!=="object"||Array.isArray(r)))throw new Error("Published ledger contains malformed records");if(key==="runs"){const ai=await checkedJson("data/ai-runs.json");if(!Array.isArray(ai)||ai.some(r=>!r||typeof r!=="object"||Array.isArray(r)))throw new Error("AI run ledger contains malformed records");return [...rows,...ai.map(r=>({...r,branch:"ai"}))];}return rows;})();try{return await pendingTables[key];}finally{delete pendingTables[key];}}
  async function loadTable(key){if(state.data[key]){renderTable(key);return;}el(`${key}-count-label`).textContent="Loading retained records…";try{const rows=await fetchTable(key);state.data[key]=rows;populateFilters(key);renderTable(key);}catch(e){el(`${key}-count-label`).textContent=`Unable to load records: ${e.message}. Reopen this section to retry.`;}}
  async function navigate(){let [section,record]=(location.hash.slice(1)||"overview").split("/");const aliases={ai:"signals",portfolio:"agent",filings:"records",transactions:"records",reviews:"records",runs:"operations"};if(aliases[section]){record=section;section=aliases[section];}
    if(section==="notifications"){openDialog("notifications-dialog",el("changes-card"));section="overview";}
    if(!["overview","signals","investor-edge","agent","records","operations"].includes(section))section="overview";
    state.section=section;state.record=["filings","transactions","reviews"].includes(record)?record:"filings";
    document.querySelectorAll(".destination").forEach(n=>n.hidden=n.id!==section);document.querySelectorAll("[data-section]").forEach(a=>{if(a.dataset.section===section)a.setAttribute("aria-current","page");else a.removeAttribute("aria-current");});
    for(const key of ["filings","transactions","reviews"])el(`panel-${key}`).hidden=key!==state.record;
    document.querySelectorAll("[data-record]").forEach(a=>{if(a.dataset.record===state.record)a.setAttribute("aria-current","page");else a.removeAttribute("aria-current");});
    el("review-categories").hidden=state.record!=="reviews";
    if(section==="investor-edge")await loadEdge();if(section==="records")await loadTable(state.record);if(section==="signals")await loadTable("ai");if(section==="agent")await loadTable("portfolio");if(section==="operations")await loadTable("runs");
  }
  async function loadEdge(){try{const edge=await checkedJson("data/investor-edge.json");if(!Array.isArray(edge.investors))throw new Error("Profile inventory unavailable");const profiles=edge.investors.filter(p=>p&&typeof p==="object");const ready=profiles.filter(p=>p.status!=="insufficient_data"&&p.minimum_sample_met!==false&&numeric(p.sample_count)!==null&&p.sample_count>=3);el("edge-history-label").textContent=ready.length?`${number(ready.length)} profiles with sufficient completed observations`:"Building history — insufficient completed observations";el("edge-history-note").textContent=profiles.length?profiles.slice(0,8).map(p=>`${p.filer||"Unknown filer"} / ${p.owner||"Unknown owner"}: n = ${number(p.sample_count)}, ${p.confidence_label||"confidence unavailable"}`).join(" · "):"Building history — insufficient completed observations (n = 0). No profiles are currently published.";}catch{el("edge-history-label").textContent="Investor Edge data unavailable";el("edge-history-note").textContent="Open the retained heat map and drilldowns for published evidence; this profile summary could not refresh.";}}
  function renderCharts(m){const c=m.coverage,max=Math.max(1,c.cataloged_only,c.processed,c.review_required,c.transactions,c.analyses,c.qualifying_signals);
    el("coverage-chart").innerHTML=[["Cataloged only",c.cataloged_only],["Processed filings",c.processed],["Review-required filings",c.review_required],["Parsed transactions",c.transactions],["AI analyses",c.analyses],["Qualifying signals",c.qualifying_signals]].map(([label,count])=>`<div class="coverage-row"><span>${label}</span><strong>${number(count)}</strong><svg class="coverage-bar" viewBox="0 0 100 3" preserveAspectRatio="none" aria-hidden="true"><rect width="${100*count/max}" height="3" rx="1"/></svg></div>`).join("");
    const p=m.composition,total=p.population,den=Math.max(1,total),purchase=p.purchases/den*300,sales=p.sales/den*300;
    el("composition-chart").innerHTML=`<div class="mix-heading"><strong>${number(total)}</strong><span>parsed transactions</span></div><svg class="mix-svg" viewBox="0 0 300 16" preserveAspectRatio="none" role="img" aria-label="${number(p.purchases)} purchases; ${number(p.sales)} sales or dispositions; ${number(p.other)} exchanges or other"><rect x="0" width="${purchase}" height="16" class="mix-purchase"/><rect x="${purchase}" width="${sales}" height="16" class="mix-sale"/><rect x="${purchase+sales}" width="${p.other/den*300}" height="16" class="mix-other"/></svg><div class="mix-legend">${[["Purchases",p.purchases,""],["Sales / dispositions",p.sales,"sale"],["Exchanges / other",p.other,"other"]].map(([l,n,c])=>`<div><span class="swatch ${c}" aria-hidden="true"></span>${l}<b>${number(n)}</b></div>`).join("")}</div>`;
    el("health-chart").innerHTML=healthCards(m);el("operations-health").innerHTML=healthCards(m,true);
  }
  function renderModel(m,change){const summary={repository_url:m.repository_url};const signalCount=m.coverage.qualifying_signals;
    el("overall-state").className=`status ${m.health.status}`;el("overall-state").textContent=m.health.status==="success"?"✓ Latest runs successful":m.health.status==="failure"?"! Attention required":"◌ Evidence incomplete";
    el("updated-at").textContent=`Data as of ${date(m.data_through_utc)}`;
    el("attention-signals").textContent=number(signalCount);el("nav-signal-count").textContent=number(signalCount);
    const delta=Object.values(change.changes||{}).filter(v=>typeof v==="number").reduce((a,b)=>a+b,0);el("attention-changes").textContent=change.firstVisit?"0":number(delta);el("attention-changes-note").textContent=change.firstVisit?"Baseline established quietly":"Changes on this browser";
    el("baseline-note").textContent=change.firstVisit?"Current records are your starting baseline. Future changes are tracked on this browser and device only.":"Compared with the previous successful review on this browser and device. Not synchronized account state.";
    el("attention-exceptions").textContent=number(m.reviews.manual_exception);el("attention-review-note").textContent=`${number(m.reviews.access_required)} access/request required · informational`;
    el("attention-health").textContent=m.health.status==="success"?"Operational":m.health.status==="failure"?"Attention":"Unknown";el("attention-health").className=`health-metric ${m.health.status}`;
    el("situation-brief").textContent=brief(m,change.changes);
    el("overview-signals").innerHTML=m.signals.length?m.signals.slice(0,2).map(s=>signalCard(s)).join(""):emptySignals(m);
    el("all-signals").innerHTML=m.signals.length?m.signals.map(s=>signalCard(s)).join("")+(m.signals_truncated?'<p class="notice">Showing the first 48 qualifying cards. All analyses remain available in the table and CSV below.</p>':""):emptySignals(m);
    renderCharts(m);
    const bad=m.health.branches.filter(b=>b.status!=="success");
    el("exceptions-list").innerHTML=bad.map(b=>`<div class="activity-row"><span class="${b.status}" aria-hidden="true">!</span><div><strong>${esc(title(b.branch))}: ${statusText(b.status)}</strong><p>${esc(b.errors.join("; ")||"No retained evidence. Do not assume healthy.")}</p>${link(b.run_url,"Run evidence")}</div></div>`).join("")+m.reviews.latest.filter(r=>r.category==="manual_exception").slice(0,2).map(r=>`<div class="activity-row"><span class="caution" aria-hidden="true">!</span><div><strong>Manual/parser exception · ${esc(r.filer||"Unknown filer")}</strong><p>${esc(r.reason)}</p>${link(r.source_url,"Review filing")}</div></div>`).join("")+`<div class="activity-row"><span aria-hidden="true">ⓘ</span><div><strong>${number(m.reviews.access_required)} access/request-required records</strong><p>Disclosure access inventory, not a red system failure. ${number(m.reviews.other)} other/uncategorized review items.</p></div></div>`;
    el("review-categories").textContent=`Manual/parser exceptions: ${number(m.reviews.manual_exception)} · Access/request required: ${number(m.reviews.access_required)} (informational) · Other/uncategorized: ${number(m.reviews.other)}`;
    el("ten-k-simulation-result").innerHTML=replay(m);el("ten-k-simulation-status").textContent=title(m.simulation.status);el("paper-position-status").textContent=m.paper.open_positions?`${number(m.paper.open_positions)} open simulated positions. Separate from historical replay.`:"No open paper positions. No performance implied.";
    el("edge-history-label").textContent="Inspect the evidence behind every profile.";el("edge-history-note").textContent="The complete heat map retains profile observation counts (n), confidence, owner separation, methodology and all trade-level drilldowns. Missing alpha or returns remain unavailable.";
    el("inventory-summary").innerHTML=`<dl class="facts">${fact("Cataloged filings",number(m.coverage.filings))}${fact("Parsed transactions",number(m.coverage.transactions))}${fact("AI analyses",number(m.coverage.analyses))}${fact("Review inventory",number(m.reviews.total))}</dl>`;el("coverage-note").textContent=m.coverage.note;
    el("build-details").textContent=`Published build ${m.build_sha||"unavailable"} · generated ${date(m.generated_utc)} · data ${age(m.data_through_utc)}`;
    el("run-simulation-link").href=workflowUrl(summary.repository_url)||"#";el("run-10k-agent-link").href=workflowUrl(summary.repository_url, "filing_simulation.yml")||"#";el("repository-link").href=safeUrl(m.repository_url)||"#";
    const tests=Object.values(m.synthetic).reduce((a,b)=>a+b,0);el("manual-test-notice").hidden=!tests;el("manual-test-note").textContent=`${number(m.synthetic.filings)} synthetic filings and ${number(m.synthetic.transactions)} synthetic transactions excluded from the production Overview. TEST records remain in detailed records.`;
  }
  function notificationEvidence(url){return /^#[\w/-]+$/.test(url||"")?`<a href="${esc(url)}" data-notification-link>View evidence →</a>`:link(url,"Evidence");}
  function renderNotifications(){const s=notifications.getState(),focused=document.activeElement,focusKeys=["ack","snooze","mute"],focusKey=focusKeys.find(key=>focused?.dataset?.[key]),focusValue=focusKey?focused.dataset[focusKey]:null;el("notification-count").textContent=number(s.unread);el("notification-button").setAttribute("aria-label",`Notification Center, ${s.unread} unread, ${s.actionable} actionable`);el("notification-summary").textContent=`${s.unread} unread · ${s.actionable} actionable`;
    el("sound-button").textContent=s.settings.mode==="off"?"Sound off":s.sound.armed?"Sound armed":"Sound unarmed";el("sound-status").textContent=s.sound.status||"Sound is off.";
    el("notification-storage-note").hidden=s.storageAvailable;el("notification-storage-note").textContent="Browser storage unavailable. History cannot persist; automatic sound remains silent.";
    el("notification-list").innerHTML=s.events.length?s.events.map(e=>`<article class="notification-item ${e.acknowledged?"acknowledged":""}"><header><strong class="${e.severity==="high"?"positive":e.severity==="warning"?"caution":e.severity==="success"?"success":"muted"}">${esc(e.icon)} ${esc(title(e.severity))}${e.simulation?" · SIMULATED":""}</strong><time>${esc(date(e.timestamp))}</time></header><p>${esc(e.summary)}</p><small>${e.acknowledged?"Acknowledged":s.settings.mutedCategories[e.category]?"Category muted":e.snoozedUntil&&Date.parse(e.snoozedUntil)>Date.now()?`Snoozed until ${esc(date(e.snoozedUntil))}`:"Unread"}</small><div class="event-controls">${notificationEvidence(e.link)}<button data-ack="${esc(e.id)}" ${e.acknowledged?"disabled":""}>Acknowledge</button><button data-snooze="${esc(e.id)}">Snooze 1h</button></div></article>`).join(""):'<p class="empty">No new events on this browser. Initial records establish a quiet baseline.</p>';
    el("recent-changes").innerHTML=s.events.length?s.events.slice(0,4).map(e=>`<div class="activity-row"><span aria-hidden="true">${esc(e.icon)}</span><div><strong>${esc(e.summary)}</strong><small>${esc(title(e.severity))} · ${esc(date(e.timestamp))}${e.simulation?" · SIMULATED":""}</small></div></div>`).join(""):'<p class="empty">No new activity since your browser baseline. Existing records were not marked as new.</p>';
    el("sound-mode").value=s.settings.mode;el("sound-volume").value=Math.round(s.settings.volume*100);el("quiet-enabled").checked=!!s.settings.quietHours.enabled;el("quiet-start").value=s.settings.quietHours.start;el("quiet-end").value=s.settings.quietHours.end;
    el("mute-categories").innerHTML='<legend>Mute by event category (local only)</legend>'+[["signals","Qualifying signals"],["operations","Run incidents & recoveries"],["simulation","Simulation / replay results"],["records","Grouped record changes"]].map(([c,label])=>`<label class="check-label"><input type="checkbox" data-mute="${c}" ${s.settings.mutedCategories[c]?"checked":""}> ${label}</label>`).join("");
    if(focusKey){const replacement=[...document.querySelectorAll(`[data-${focusKey}]`)].find(node=>node.dataset[focusKey]===focusValue);if(replacement&&!replacement.disabled)replacement.focus({preventScroll:true});else if(focusKey==="ack"){el("notification-summary").setAttribute("tabindex","-1");el("notification-summary").focus({preventScroll:true});}}
    if(s.limitedCategories.length&&state.model){el("attention-changes-note").textContent="Some local comparisons unavailable";el("baseline-note").textContent="A retained category exceeds this browser's bounded comparison history. Its change count is suppressed to avoid marking old records as new.";}
  }
  async function notificationAction(action){try{await action();renderNotifications();return true;}catch{el("notification-storage-note").hidden=false;el("notification-storage-note").textContent="This browser-local change could not be saved. Try again; external alert settings are unchanged.";return false;}}
  async function loadData(){if(state.loading)return;state.loading=true;el("refresh-button").disabled=true;try{
    const model=PT.validateModel(await checkedJson("data/dashboard-insights.json"));
    // Stage open datasets as well; a partial fetch never advances the browser baseline.
    const staged={};for(const key of Object.keys(state.data))staged[key]=await fetchTable(key);
    const change=notifications.prepare(model),previous=state.model,oldData=state.data; if(change.olderSnapshot)throw new Error("Older publication rejected; keeping the last successful review");
    try{renderModel(model,change);state.data={...state.data,...staged};for(const key of Object.keys(staged)){populateFilters(key);renderTable(key);}}
    catch(e){state.data=oldData;if(previous)renderModel(previous,{changes:{},firstVisit:false});throw e;}
    state.model=model;state.renderedAt=Date.now();state.nextRefreshAt=Date.now()+300000;el("error-banner").hidden=true;
    await change.commit();renderNotifications();if(change.events.length){document.querySelectorAll(".attention-card").forEach(n=>n.classList.add("changed"));setTimeout(()=>document.querySelectorAll(".attention-card").forEach(n=>n.classList.remove("changed")),1200);}
  }catch(e){el("error-banner").textContent=`Refresh unavailable — ${e.message}. ${state.model?"Last successfully rendered data remains visible; this view may be stale.":"No successful data load yet. Status is Unknown."}`;el("error-banner").hidden=false;el("overall-state").textContent="! Refresh unavailable";el("overall-state").className="status failure";state.nextRefreshAt=Date.now()+300000;}finally{state.loading=false;el("refresh-button").disabled=false;}}
  function clock(){el("clock").textContent=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});const s=Math.max(0,Math.ceil((state.nextRefreshAt-Date.now())/1000));el("refresh-countdown").textContent=`Next refresh ${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`;}
  initTables();window.addEventListener("hashchange",()=>navigate());el("refresh-button").onclick=loadData;
  document.addEventListener("click",e=>{const a=e.target.closest("[data-ack]"),s=e.target.closest("[data-snooze]");if(a)notificationAction(()=>notifications.acknowledge(a.dataset.ack));if(s)notificationAction(()=>notifications.snooze(s.dataset.snooze,60));if(e.target.closest("[data-notification-link]"))el("notifications-dialog").close();});
  el("acknowledge-all").onclick=()=>notificationAction(()=>notifications.acknowledge("all"));
  el("mute-categories").addEventListener("change",e=>{if(e.target.dataset.mute){const category=e.target.dataset.mute,muted=e.target.checked;notificationAction(()=>notifications.mute(category,muted));}});
  el("sound-mode").onchange=e=>notificationAction(()=>notifications.setSettings({mode:e.target.value}));el("sound-volume").onchange=e=>notificationAction(()=>notifications.setSettings({volume:Number(e.target.value)/100}));
  for(const id of ["quiet-enabled","quiet-start","quiet-end"])el(id).onchange=()=>notificationAction(()=>notifications.setSettings({quietHours:{enabled:el("quiet-enabled").checked,start:el("quiet-start").value,end:el("quiet-end").value}}));
  el("enable-sound").onclick=e=>notificationAction(()=>notifications.enableSound(e));el("test-sound").onclick=e=>notificationAction(()=>notifications.testSound(e));
  setInterval(clock,1000);setInterval(loadData,300000);clock();renderNotifications();navigate();loadData();
})();
