(() => {
  "use strict";
  const DEFAULT_REFRESH_SECONDS = 300;
  const {el,esc,number,title,date,age,safeUrl,link,workflowUrl,checkedJson,statusText,emptySignals,signalCard,replay,brief}=PT;
  const params=new URLSearchParams(location.search),requested=Number(params.get("refresh")||DEFAULT_REFRESH_SECONDS),refreshSeconds=Math.min(1800,Math.max(60,Number.isFinite(requested)?requested:DEFAULT_REFRESH_SECONDS));
  const state={data:null,nextRefreshAt:Date.now()+refreshSeconds*1000,wakeLock:null,loading:false,changes:{}};
  PT.setupDialogsAndTooltips();const notices=new PolitiTrackNotifications({onChange:renderSound});
  function renderSound(){const s=notices.getState();el("wall-sound").textContent=s.settings.mode==="off"?"Sound off":s.sound.armed?"Sound armed":"Sound muted / unarmed";el("wall-sound").setAttribute("aria-label",`${el("wall-sound").textContent}. ${s.sound.status}. Browser-local sound only.`);}
  function render(m,changes={}){const summary={repository_url:m.repository_url};
    el("wall-run-simulation-link").href=workflowUrl(summary.repository_url)||"#";el("wall-run-10k-agent-link").href=workflowUrl(summary.repository_url, "filing_simulation.yml")||"#";
    el("situation-brief").textContent=brief(m,changes);el("overall-state").textContent=m.health.status==="success"?"✓ Latest runs successful":m.health.status==="failure"?"! Attention required":"◌ Evidence unknown";el("overall-state").className=`status ${m.health.status}`;
    el("source-strip").innerHTML=m.health.branches.map(b=>`<div class="wall-source"><div><strong>${b.branch==="ai"?"AI analyst":esc(title(b.branch))}</strong><p>Last run ${esc(age(b.last_run_utc))} · success ${esc(age(b.last_success_utc))} · ${number(b.new_record_count)} new</p></div><span class="status ${esc(b.status)}">${statusText(b.status)}</span></div>`).join("");
    el("metric-high").textContent=number(m.coverage.qualifying_signals);el("metric-review").textContent=number(m.reviews.manual_exception);el("access-count").textContent=`${number(m.reviews.access_required)} access/request required`;
    el("metric-open-positions").textContent=number(m.paper.open_positions);el("metric-changes").textContent=number(Object.values(changes).filter(v=>typeof v==="number").reduce((a,b)=>a+b,0));
    el("candidate-list").innerHTML=m.signals.length?m.signals.slice(0,2).map(s=>signalCard(s,true)).join(""):emptySignals(m);
    el("wall-ten-k-simulation").innerHTML=replay(m,true);el("filing-count").textContent=`${number(m.coverage.filings)} cataloged`;
    el("filing-list").innerHTML=m.latest_filings.slice(0,5).map(f=>`<div class="activity-row"><div><strong>${esc(f.filer||"Unknown filer")}</strong><p>${esc(title(f.source))} · filed ${esc(date(f.filed_date))} · ${esc(title(f.status))}</p>${link(f.source_url)}</div></div>`).join("")||'<p class="empty">No retained filing inventory.</p>';
    el("review-list").innerHTML=m.health.branches.filter(b=>b.status!=="success").map(b=>`<div class="activity-row"><div><strong class="caution">${esc(title(b.branch))}: ${statusText(b.status)}</strong><p>${esc(b.errors.join("; ")||"No retained evidence.")}</p></div></div>`).join("")+`<p>${number(m.reviews.manual_exception)} manual/parser exceptions · ${number(m.reviews.access_required)} access-required records (informational).</p>`;
    el("portfolio-list").textContent=m.paper.open_positions?`${number(m.paper.open_positions)} open PAPER TRADING positions. See full dashboard for each valuation.`:"No open paper positions. No performance implied.";
    renderSound();updateClock();
  }
  async function loadData(){if(state.loading)return;state.loading=true;try{const m=PT.validateModel(await checkedJson("data/dashboard-insights.json"));const change=notices.prepare(m);if(change.olderSnapshot)throw new Error("Older publication rejected; keeping last-known data");try{render(m,change.changes);}catch(e){if(state.data)render(state.data,state.changes);throw e;}state.data=m;state.changes=change.changes;await change.commit();el("error-banner").hidden=true;renderSound();}catch(e){el("error-banner").textContent=`Refresh unavailable — ${e.message}. Existing data remains on screen; it may be stale.`;el("error-banner").hidden=false;el("overall-state").textContent="! Refresh unavailable";el("overall-state").className="status failure";}finally{state.loading=false;state.nextRefreshAt=Date.now()+refreshSeconds*1000;}}
  function updateClock(){const now=new Date();el("clock").textContent=now.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"});el("clock-date").textContent=now.toLocaleDateString([], {weekday:"short",month:"short",day:"numeric"});const remaining=Math.max(0,Math.ceil((state.nextRefreshAt-Date.now())/1000));el("refresh-countdown").textContent=`Data refresh in ${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,"0")}`;if(state.data){el("data-through").textContent=`Data as of ${date(state.data.data_through_utc)}`;el("freshness").textContent=`Data ${age(state.data.data_through_utc)}`;}}
  function updateOrientationLabel(){const portrait=innerHeight>innerWidth;el("orientation-label").textContent=`${portrait?"Portrait wallboard":innerWidth/innerHeight>=2.4?"Super-ultrawide wallboard":"Responsive wallboard"} · ${innerWidth} × ${innerHeight} · CHG90 target 1080 × 3840`;}
  async function requestWakeLock(){if(!("wakeLock"in navigator))return;try{state.wakeLock=await navigator.wakeLock.request("screen");}catch{state.wakeLock=null;}}
  async function toggleFullscreen(){try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else if(document.fullscreenElement&&document.exitFullscreen)await document.exitFullscreen();}catch{el("fullscreen-button").textContent="Fullscreen unavailable";}await requestWakeLock();}
  el("fullscreen-button").onclick=toggleFullscreen;document.addEventListener("fullscreenchange",()=>{el("fullscreen-button").textContent=document.fullscreenElement?"Exit full screen":"Full screen";});document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&document.fullscreenElement)requestWakeLock();});window.addEventListener("resize",updateOrientationLabel);
  el("wall-sound").onclick=async e=>{try{const s=notices.getState();if(s.sound.armed&&s.settings.mode!=="off")await notices.setSettings({mode:"off"});else await notices.enableSound(e);renderSound();}catch{el("wall-sound").textContent="Sound unavailable";el("wall-sound").setAttribute("aria-label","Browser-local sound update unavailable. Visual status and external alerts are unchanged.");}};
  setInterval(updateClock,1000);setInterval(loadData,refreshSeconds*1000);updateClock();updateOrientationLabel();renderSound();loadData();
})();
